### ISSUE TITLE
make nonpareil-mpi

### ISSUE THREAD

**Issue by chengchenye** [lmrodriguezr/nonpareil#16] opened 2016-10-11 05:07 UTC
I am getting this problem when compiling  .
The code produces the following warnings when compiling with mpic++:
make mpicpp=/mnt/ilustre/users/chengchen.ye/software/openmpi/bin/mpic++ nonpareil-mpi 
cd enveomics/ && make nonpareil-mpi
make[1]: Entering directory `/mnt/ilustre/users/chengchen.ye/project/Nonpareil/lmrodriguezr-nonpareil-92e9a25/enveomics'
/mnt/ilustre/users/chengchen.ye/software/openmpi/bin/mpic++ -DENVEOMICS_MULTI_NODE universal.cpp -c -Wall
/mnt/ilustre/users/chengchen.ye/software/openmpi/bin/mpic++ -DENVEOMICS_MULTI_NODE multinode.cpp -c -Wall
multinode.cpp: 在函数‘void init_multinode(int&, char**&, int&, int&)’中:
multinode.cpp:16:4: 错误：‘MPI’未声明
    MPI::Init(argc, argv);
    ^
multinode.cpp:17:16: 错误：‘MPI’未声明
    processes = MPI::COMM_WORLD.Get_size();
                ^
multinode.cpp:18:16: 错误：‘MPI’未声明
    processID = MPI::COMM_WORLD.Get_rank();
                ^
multinode.cpp: 在函数‘void finalize_multinode()’中:
multinode.cpp:21:4: 错误：‘MPI’未声明
    MPI::Finalize();
    ^
multinode.cpp: 在函数‘void barrier_multinode()’中:
multinode.cpp:25:4: 错误：‘MPI’未声明

**Comment by lmrodriguezr** [comment] 2017-05-19 18:54
I cannot reproduce this error. Do you have the developer libraries of MPI?

**Comment by lmrodriguezr** [comment] 2022-01-28 18:06
I'm closing this issue since I didn't get responses back, but if anyone is able to reproduce it please feel free to reopen.

**Closed by lmrodriguezr** 2022-01-28 18:06 UTC
